### PR TITLE
Update old illustrations and add new ones

### PR DESCRIPTION
**Pull request by stephen-tl**
This commit adds new illustrations in new sizes and updates older versions.

### Updated

- 120x120_billing_static.svg
- 120x120_contacts_static.svg
- 120x120_crowd_static.svg
- 120x120_deals_static.svg
- 120x120_female_static.svg
- 120x120_invoices_static.svg
- 120x120_male_static.svg
- 120x120_marketing_static.svg
- 120x120_meetings_static.svg
- 120x120_phone_static.svg
- 120x120_planning_static.svg
- 120x120_search_static.svg
- 120x120_sent_static.svg
- 120x120_sharpies_static.svg
- 90x90_gift_static.svg

### Added

- 120x120_blueprint_static.svg
- 120x120_books_static.svg
- 120x120_forms_static.svg
- 120x120_integrationfund_static.svg
- 120x120_manage_static.svg
- 120x120_movie_static.svg
- 120x120_projects_static.svg
- 120x120_puzzle_static.svg
- 120x120_puzzlescatter_static.svg
- 120x120_puzzleworkflow_static.svg
- 120x120_rocket_static.svg
- 120x120_seal_static.svg
- 200x200_calendar_static.svg
- 200x200_crm_static.svg
- 200x200_folder_static.svg
- 200x200_hands_static.svg
- 200x200_headset_static.svg
- 200x200_invoice_static.svg
- 200x200_stopwatch_static.svg
- 200x200_tickets_static.svg
- 240x240_dragon_static.svg
- 240x240_grow_static.svg
- 240x240_recycle bin_static.svg
- 240x240_stuff_static.svg
- 60x60_crm_static.svg
- 60x60_invoices_static.svg
- 60x60_projects_static.svg
- 60x60_tasks_static.svg
- 90x90_calls_static.svg
- 90x90_emails_static.svg
- 90x90_meetings_static.svg
- 90x90_paperplane_static.svg
- 90x90_tasks_static.svg

### CODE REVIEW

**Comment by LennertBlommaert** [comment]
Q: Shouldn't we also minify the new `svg`s? (Seems like the old ones were)

**Comment by stephen-tl** [comment]
@stephen-tl they should be compressed since I'm using the SVGO on Sketch to export them. If there is a way to minify them even more, feel free to tell me how :)

**Comment by stephen-tl** [comment]
@InstaK Assuming you minified the previous versions to be a 0ne-liner. Can you tell me how I get these SVG's minified into a one-liner? #designerquestions

**Comment by driesd** [comment]
@kevin, good point, but this is the `visuals` repository containing illustrations where colors should not be overridable.

**Comment by InstaK** [comment]
@driesd 	ok perfect, just wanted to raise awareness 😊

**Pull request merged**
